### ISSUE TITLE
Solana - fees?

### ISSUE THREAD

**Issue by showered** [kinecosystem/technology#2]
Hi @kikengineering 

Your proposal looks excellent and exciting!

I noticed that there was no mention of fees on Solana.

Do you have any insight on this?

As a developer I don't really care much about whitelisting if the fees are tiny (like on Stellar). But it's critical, in my opinion, that Users don't pay fees. Perhaps there could be a similar process whereby the User creates the tx, and then the App signs it and pays for it?

**Comment by NeonGameStudios** [comment]
[Transaction fees are not an issue, according to Solana.](https://www.reddit.com/r/KinFoundation/comments/gokl7r/hey_everyone_the_official_solana_reddit_account/frgdg18?utm_source=share&utm_medium=web2x)

> At the current state it costs $0.00001 for over 1 million transactions.

**Comment by skyf0xx** [comment]
@NeonGameStudios - More accurately, fees are $0.00001 per transaction, from their homepage. I think the idea is, if Kin transactions are in the range of $0.01 - then the fees are 'negligible'.

You would probably need to keep the client supplied with solana sols to pay gas - so that all Kin transactions are 'free'. I imagine the client could query the server for more sols when it's about to run out.

**Comment by NeonGameStudios** [comment]
@hitwill You are correct that there is a discrepancy between what they posted and their website.  It seems impossible that 1 million transactions are so cheap... but it would make Kin future proof for many years hopefully!
